# Helm values for cu-ms-payments
# Chart: juanjcordero/helm-microservice-chart:1.0.3

# Configuración básica del microservicio
name: cu-ms-payments
namespace: juanjcordero-dev
imageTag: "1" # Será sobrescrito por CI/CD con --set imageTag=<value>
port: 3005

# Variables de entorno (ConfigMap)
configMap:
  LOG_LEVEL: "debug"
  MICROSERVICE_URL: "http://cu-ms-payments:3000"  # URL del microservicio 2

  # Secrets (valores en base64)


# Secrets (valores en base64)
secret:
  DATABASE_PASSWORD: TWlQYXNzd29yZFNlZ3VybzEyMw==

# Horizontal Pod Autoscaler
hpa:
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 90
  memoryUtilization: 90